name: Build Static Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: maclong9/web-ui/.github/workflows/build-optimized.yml@main
    with:
      webui-cli-version: 'latest'
      output-directory: '.output'
      static-branch: 'static'
