name: Build Static Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build:
    runs-on: macos-15
    steps:
      # Check out the repository code
      - uses: actions/checkout@v4
      
      # Cache Swift toolchain (stable key)
      - name: Cache Swift Toolchain
        uses: actions/cache@v4
        id: cache-swift-toolchain
        with:
          path: ~/Library/Developer/Toolchains
          key: ${{ runner.os }}-swift-toolchain-v1
          restore-keys: |
            ${{ runner.os }}-swift-toolchain-

      # Set up Swift (only if cache miss)
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        if: steps.cache-swift-toolchain.outputs.cache-hit != 'true'
      
      # Cache Swift build artifacts (more specific key)
      - name: Cache Swift Build
        uses: actions/cache@v4
        id: cache-swift-build
        with:
          path: .build
          key: ${{ runner.os }}-swift-build-${{ hashFiles('Package.swift', 'Package.resolved') }}-${{ hashFiles('Sources/**/*.swift') }}
          restore-keys: |
            ${{ runner.os }}-swift-build-${{ hashFiles('Package.swift', 'Package.resolved') }}-
            ${{ runner.os }}-swift-build-
      
      # Build the project (always run, but will be fast with cache)
      - name: Build
        run: swift build -v
      
      # Cache generated site output (more targeted)
      - name: Cache Generated Site
        uses: actions/cache@v4
        id: cache-site-output
        with:
          path: .output
          key: ${{ runner.os }}-site-output-${{ hashFiles('Sources/**/*.swift', 'Public/**', 'Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-site-output-
      
      # Run the static site generator
      - name: Generate Site
        run: swift run Application
        if: steps.cache-site-output.outputs.cache-hit != 'true'

      # Push to static branch (only on push to main)
      - name: Push to static branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git checkout -B static
          rm -rf ./*
          mv .output/* .
          rm -rf .output .gitignore .github .build .swift-format Public
          git add .
          git commit -m "Update static site content"
          git push origin static --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
